management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
        product-service:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            sliding-window-type: COUNT_BASED
  retry:
    instances:
      product-service:
        max-attempts : 3
        wait-duration: 1s
        retry-exceptions:
  ratelimiter:
    instances:
        product-service:
            limit-for-period: 5
            limit-refresh-period: 10s
            timeout-duration: 10s
            event-consumer-buffer-size: 10